# Generated by Django 6.1.1 on 2026-09-28 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_catalogo_calculadora'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemaAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(choices=[('plaga', 'Plaga'), ('enfermedad', 'Enfermedad'), ('maleza', 'Maleza'), ('nutricion', 'Nutrición')], default='plaga', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('sintomas', models.TextField(blank=True)),
                ('manejo', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='cultivo',
            name='ciclo_dias',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='epoca',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='familia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='notas_manejo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='carencia_dias',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='consideraciones_seguridad',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='fuente',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='insumo',
            name='ingrediente_activo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='insumo',
            name='modo_aplicacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='insumo',
            name='problema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos', to='core.problemaagricola'),
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('ciclo_dias', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variedades', to='core.cultivo')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variedades', to='core.zona')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarioSiembra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_siembra_inicio', models.PositiveSmallIntegerField()),
                ('mes_siembra_fin', models.PositiveSmallIntegerField()),
                ('mes_cosecha_inicio', models.PositiveSmallIntegerField()),
                ('mes_cosecha_fin', models.PositiveSmallIntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios', to='core.cultivo')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendarios', to='core.zona')),
                ('variedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendarios', to='core.variedad')),
            ],
        ),
    ]
